### ISSUE TITLE
New Release 1.3

### ISSUE THREAD

**Issue by Remco75** [apigee-127/swagger-test-templates#105]
Hi, 
Could you please release the current master (1.3?, 1.2.x? )? The added json-deref makes it worth-while. Also on npm would be nice ;-)

Thnx!

**Comment by noahdietz** [comment]
@Remco75 @mm-gmbd I will cut a new release (probably a 1.3.0), but I want to make sure we get the right stuff/not leave anyone out. Both of you have been active on this project and I would _really_ appreciate the help. 

Please post on this thread what issues/PRs you want to see merged prior to a 1.3.0 release. 

I merged @Remco75's PR for custom template config, so that is in.
#104 will probably be resolved by releasing the latest as there is deref code in master
#107 Would be awesome, considering others requested it. @mm-gmbd if you could check out the test [Travis](https://travis-ci.org/apigee-127/swagger-test-templates/builds/156516342) failures that'd be great.

**Comment by mm-gmbd** [comment]
@noahdietz -- I'd be happy to check out and resolve the failures, but I did notice them when I opened the PR and wasn't quite sure how to mitigate. I'm not a Travis whiz :)

![image](https://cloud.githubusercontent.com/assets/3329824/18138724/1d311cd0-6f7c-11e6-93a7-13f1de7c1b75.png)

I didn't *remove* any environment variables, so what environment variables need to be set? Thanks!

**Comment by mm-gmbd** [comment]
Oops -- I thought this was on the PR, sorry! Moving discussion on Travis failure to the PR...

**Comment by Remco75** [comment]
Cool lot's of activity all of the sudden! 
I agree, #104 can be closed after release of master. Although we still are lacking support for the formats like int64 int32 etc that z-schema does not know about. #99 was attempting to solve that (as well as myself in a PR I closed because of duplication.  I will look into the #99 PR and see what I can do tomorrow.

**Comment by noahdietz** [comment]
I want to add #109 as the last thing before I cut a new release. Travis running against some pretty old versions of node...

**Comment by Maples7** [comment]
So, any plan to release 1.3.0? I'm looking forward to it!!! And, please let me know after release. :wink:

**Comment by Remco75** [comment]
@Maples7 , yes, it's coming.... soon ;-)
We want #107 to be in there, so if you can help out there, feel free to join the development.

**Comment by Maples7** [comment]
@Remco75 
Awesome job!!! This would make API tests much easier! 
I'll have a try when I get some time~

**Comment by Remco75** [comment]
@Maples7 , thnx, but also thank @noahdietz and @mm-gmbd ! :-)

**Comment by jamesabc** [comment]
Can we get a `1.3.0` with configurable `templatesPath` feature and push #107 back to `1.4.0`?  I would be very happy...

**Comment by Remco75** [comment]
yes, I agree that this is taking too long. (release small , release often should be the way to go)
@noahdietz @mm-gmbd , a proposal: let's release at 14 oktober, regardless we have finished everything we wanted.
I hope we can find the time te review #119 so we can close some bugs and PR's. If not: 1.4 it is!
lemme know your thoughts

**Comment by noahdietz** [comment]
sgtm
