### ISSUE TITLE
Feature request: configurable swagger.yaml and test output location

### ISSUE THREAD

**Issue by jamesabc** [apigee-127/swagger-test-templates#121]
First, thanks for the awesome package.  Saves typing a lot of boilerplate!

Our issue is that we're using this in an existing project with an already existing directory structure for test files.  It would be nice if the location of the swagger.yaml and the directory of the generated test files could be configured by command-line arguments so we could run this script without having to move the generated files afterwards.

**Comment by noahdietz** [comment]
Hey @jamesabc ! First, thank you lots for using the module and opening this feature request. Love seeing an active user base.

As for your request, I don't think this is an issue with the module as is. Are you using it through the `swagger-node` project? 

The module as is returns an array of objects containing the file names and the actual file contents as a string. This is because we didn't want to force a directory structure when using the module alone. You can iterate over this set of objects and write the files wherever you'd like!

As for the swagger.yaml, this is a bit trickier. `swagger-node` had the added benefit of converting the yaml into json, easier for us to parse, which is what this module takes as input. So if you can convert your yaml into json, just `require` it in your own script and pass it to this module!

For an example of the basic usage, check out the README.

Thanks again for using the module and let me know if I can help more or if this can be closed.

**Comment by jamesabc** [comment]
Ah sorry, I did not RTFM before posting :(

I am using the `swagger project generate-test` command, which does allow us to use a yaml spec without issue, but I could find no way to change the output location from there.  However, writing a custom wrapper script that uses the node interface should be a snap.  Thanks for your speedy reply!
