### ISSUE TITLE
pathified path for supertest get contains backslashes

### ISSUE THREAD

**Issue by mmmatthew** [apigee-127/swagger-test-templates#125]
The generated test files (using supertest) contain backslashes in the path for the api.get line.
(the segment shown below is generated from `templates/supertest/get/get.handlebars ` lines 6 and onwards.
Extract from my generated test file:
```
      /*eslint-enable*/
      api.get('\v1\users\verifyToken')        <<< RIGHT HERE
      .set('Content-Type', 'application/json')
      .set('x-access-token', process.env.JSONWEBTOKEN)
      .expect(200)
      .end(function(err, res) {
        if (err) return done(err);

        validator.validate(res.body, schema).should.be.true;
        done();
      });
```
Is this normal?

**Comment by noahdietz** [comment]
This is not normal, as this is not a valid URL...
@Remco75 what do you think is causing this? is it possibly this section of [pathify](https://github.com/apigee-127/swagger-test-templates/blob/master/lib/helpers.js#L109-L112)?

**Comment by Remco75** [comment]
@noahdietz I will try to find some time later this week

**Comment by svnk** [comment]
This is, because swagger-test uses path.join() to construct URLs. This works on Mac and linux, because they use slashes "/" to separate filesystem paths. But windows uses backslashes...

https://github.com/apigee-127/swagger-test-templates/blob/master/index.js#L93

http://stackoverflow.com/a/39738509 says, to use url-join instead.

**Comment by Remco75** [comment]
aah, nice one! I did not find time to dive into this one: I will try to make a PR soon, thnx @svnk
