### ISSUE TITLE
Duplicate Test Units

### ISSUE THREAD

**Issue by Murrugarra** [apigee-127/swagger-test-templates#130]
I generated some test scripts for one endpoint, but for some reason STT is creating four it() statements in the API Test Javascript file.

**Comment by noahdietz** [comment]
Hey @Murrugarra!

Can I ask, does the one endpoint have multiple responses defined in the spec?
For example (not valid spec, just pseudo code):
```
GET /user/{id}
- 200 OK
- 400 Bad Request
- 403 Unauthorized
- 500 Internal Error
```
This single endpoint, having four responses defined in its spec, will have 4 `it()` blocks because it will have 4 responses to test. 

Does that clear it up or is your situation different? If it's different, please share as much as you can about your scenario so I can help debug! Thanks!

**Comment by noahdietz** [comment]
If the question is answered, please close this issue. I will close soon if there is no response.
