### ISSUE TITLE
validator in generated tests fails due to "UNRESOLVABLE_REFERENCE"

### ISSUE THREAD

**Issue by chocstarfish** [apigee-127/swagger-test-templates#87]
In the swagger spec file, the schemas of my responses contain 
```
$ref: "#/definitions/SomeOtherResponse"
```
but swagger-test-templates failed to load the referred definitions and put them before the actual schemas, and that causes the validator failing due to "UNRESOLVABLE_REFERENCE"

**Comment by mohsen1** [comment]
How you resolve references in your swagger file before using it with this?

**Comment by chocstarfish** [comment]
In the swagger file, there's a "definitions" property ( check out [here](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#swagger-object]) ), and you can define schema objects here and reference them in other places(i.e. responses, parameters, etc) so that complex schemas can be re-used.

**Comment by noahdietz** [comment]
You need to resolve the references you make to the definitions you define so that when parsing, we have the full definition not the reference. So before using ```testGen```, you have to use the [swagger-tools](https://www.npmjs.com/package/swagger-tools) module and call ```resolve```, as it is done [here](https://github.com/swagger-api/swagger-node/blob/master/lib/commands/project/project.js#L431)

I hope this helps!

**Comment by noahdietz** [comment]
Closing as answer was given and lack of activity. Reopen if problem/confusion persists.
