### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by danwkennedy** [apigee-127/swagger-test-templates#93]
It'd be cool to be able to see a changelog so you could track new features/bug fixes.

**Comment by noahdietz** [comment]
Hi @danwkennedy there is in fact a [release log](https://github.com/apigee-127/swagger-test-templates/releases) built into Github that tracks the releases as well as the commits since the last release. Our commit history is pretty well organized, so I think you'll be able to glean the info you need :)

**Comment by noahdietz** [comment]
closing this issue as the release log/commit history is curated well enough to fulfill this request
